title: jj.created.today
url: "https://jj.created.today"
collections:
  mocs:
    output: true
    permalink: /:title/
    sort_by: year
defaults:
  - scope:
      path: ""
      type: mocs
    values:
      layout: moc
